### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by maxschram** [jpkalbacher/runwithme#2]
Where is the map component in your component hierarchy?

**Comment by jpkalbacher** [comment]
I was a little confused by the example hierarchy. Is it assumed that things like "header and footer" fall under the "app" component as they show up on every "page".

The map will really be the main page of my application. Components on the map will be the markers, the create and edit form for events and a display window for all of the events. I would like to change the UI a little from my original plan. See the image below. The box on the right side of the map is the edit/create/view box.

The page loads initially with the create form up. Clicking on a map marker that does not belong to the user brings up a show view of the event. Clicking anywhere on the map changes the view to the create form view with the coordinates already plugged in. Finally, clicking on one of your own markers brings up the edit view. I'll leave the "create event" button at the bottom right so the user can start with a fresh form instead of pre-populating with coords.

<img width="391" alt="screen shot 2015-10-13 at 7 21 49 am" src="https://cloud.githubusercontent.com/assets/7155806/10457423/1fe59046-717b-11e5-87f1-8addd837b817.png">

<img width="344" alt="screen shot 2015-10-13 at 7 18 13 am" src="https://cloud.githubusercontent.com/assets/7155806/10457321/a7342cde-717a-11e5-8658-d8f2593d93fe.png">

**\* just realized I edited the create account wireframe. Either way, the form/event show/event create components will render where the create account component is displaying now
