### ISSUE TITLE
Phase 2

### ISSUE THREAD

**Issue by maxschram** [jpkalbacher/runwithme#3]
I think there's too much going on this phase. Try to pickoff just one main feature here and split the rest out into more phases

**Comment by jpkalbacher** [comment]
Going with the new idea of having the three event components (create, edit, view) docked on the map, I think I'll split part two up by having the map show up after login for phase two. Phase three will be adding the event create/show/edit components with CRUD operations working for events. 

After phase two, users should be able to log in and be shown the map component and the header. 

I wanted to avoid this initially because I wasn't sure how to integrate the rails auth flow with react. Hopefully we'll cover it soon, or I'll start digging online.
